apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: demo-rhpam
spec:
  environment: rhpam-authoring
  commonConfig:
    adminUser: admin
    adminPassword: admin
    startupStrategy:
      strategyName: ControllerBasedStartupStrategy
  auth:
    sso:
      url: 'https://keycloak-keycloak.apps.moss.eastus.aroapp.io/auth'
      realm: moss
      disableSSLCertValidation: true
  objects:
    console:
      storageClassName: managed-csi
      routeHostname: 'https://demo-rhpam-rhpamcentr-bam-ns.apps.moss.eastus.aroapp.io'
      ssoClient:
        name: rhpam-console-client
        secret: Ekyze1lXYpO1IDT3gY2wxV5QwSR0ZRDR
        hostnameHTTPS: 'https://keycloak-keycloak.apps.moss.eastus.aroapp.io/auth'
    servers:
      - id: server1
        name: demo-rhpam-kieserver
        routeHostname: 'https://demo-rhpam-kieserver-bam-ns.apps.moss.eastus.aroapp.io'
        ssoClient:
          name: rhpam-server-client
          secret: BvNyIFrl3OrmExFDgimj2DB15a4UPBhp
          hostnameHTTPS: 'https://keycloak-keycloak.apps.moss.eastus.aroapp.io/auth'
        database:
          storageClassName: managed-csi
          type: postgresql